Ansible 2
Otus-DevOps-2022-05/klimenko-sergey_infra pull request #10
Opened 2022-07-20 19:07 UTC by klimenko-sergey

# Выполнено ДЗ "Деплой и управление конфигурацией с Ansible"

 - [+] Основное ДЗ
 - [-] Задание со *

## В процессе сделано:
 - Один playbook, один сценарий reddit_app_one_play.yml
 - Шаблон конфигурации MongoDB - mongod.conf.j2
 - Настройка инстанса веб приложения
 - Деплой веб приложения
 - Один плейбук, несколько сценариев reddit_app_multiple_plays.yml
 - Несколько плейбуков: app.yml, db.yml, deploy.yml, site.yml
 - Плейбуки для Packer: packer_app.yml, packer_db.yml
 - Изменен провижининг в packer/app.json, packer/db.json

## Как запустить проект:
 - В директории packer запустить команды:
 ```
packer build -var-file=variables.json app.json
packer build -var-file=variables.json db.json
 ```
 - В директории terraform/stage запустить команду:
 ```
terraform apply -auto-approve
 ```
 - В директории ansible запустить команду:
 ```
ansible-playbook site.yml
 ```

## Как проверить работоспособность:
 - Открыть веб приложение:
http://<public_ip_VM_with_app>:9292

## PR checklist
 - [-] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2022-07-21 12:14 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Давайте починим тесты, оставил комментарий к файлу
Приключение на 20 минут, дз возвращаю на доработку =)

2022-07-21 12:14 UTC, mrgreyves commented on ansible/inventory
>  # dbserver ansible_host=51.250.10.185 ansible_user=ubuntu ansible_private_key_file=~/.ssh/ubuntu
Вот тут не хватает расширения у файла =)

2022-07-21 13:12 UTC, klimenko-sergey commented on ansible/inventory
>  # dbserver ansible_host=51.250.10.185 ansible_user=ubuntu ansible_private_key_file=~/.ssh/ubuntu
@mrgreyves , добрый день!
Добавил расширение .ini

2022-07-21 13:19 UTC, klimenko-sergey commented on ansible/inventory
>  # dbserver ansible_host=51.250.10.185 ansible_user=ubuntu ansible_private_key_file=~/.ssh/ubuntu
Нужно ли что-то еще сделать?

2022-07-22 15:03 UTC, klimenko-sergey commented on ansible/inventory
>  # dbserver ansible_host=51.250.10.185 ansible_user=ubuntu ansible_private_key_file=~/.ssh/ubuntu
Upd.: Адаптировал шаблоны для прохождения тестов.

2022-07-26 11:16 UTC, mrgreyves requested changes
Здравствуйте!)
Давайте пофиксим расширение для файла инвентаря
Это можно сделать быстро =)
Описал в комментарии в чем проблема =)

2022-07-26 11:16 UTC, mrgreyves commented on ansible/inventory.ini
> +# appserver ansible_host=51.250.82.15 ansible_user=ubuntu ansible_private_key_file=~/.ssh/ubuntu
Так ini же должно быть расширение, а yml
По этому тесты и валяться, инвентаря то для ansible фактически нет
Это наглядно видно в тестах

2022-07-26 11:16 UTC, mrgreyves commented on ansible/inventory.ini
> +# appserver ansible_host=51.250.82.15 ansible_user=ubuntu ansible_private_key_file=~/.ssh/ubuntu
Так ini же должно быть расширение, а yml
По этому тесты и валяться, инвентаря то для ansible фактически нет
Это наглядно видно в тестах

2022-07-26 11:18 UTC, klimenko-sergey commented on ansible/inventory.ini
> +# appserver ansible_host=51.250.82.15 ansible_user=ubuntu ansible_private_key_file=~/.ssh/ubuntu
[inventory.yml](https://github.com/Otus-DevOps-2022-05/klimenko-sergey_infra/blob/main/ansible/inventory.yml) тоже есть.

2022-07-26 11:19 UTC, klimenko-sergey commented on ansible/inventory.ini
> +# appserver ansible_host=51.250.82.15 ansible_user=ubuntu ansible_private_key_file=~/.ssh/ubuntu
![изображение](https://user-images.githubusercontent.com/107353318/180993987-250b1449-dc76-4183-96b6-50d15d5e0b17.png)

2022-07-27 06:01 UTC, klimenko-sergey commented on ansible/inventory.ini
> +# appserver ansible_host=51.250.82.15 ansible_user=ubuntu ansible_private_key_file=~/.ssh/ubuntu
[inventory.yml](https://github.com/Otus-DevOps-2022-05/klimenko-sergey_infra/blob/ansible-2/ansible/inventory.yml) тоже есть.

2022-07-28 11:34 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-07-28 12:02 UTC, merged