Ansible 3
Otus-DevOps-2022-05/klimenko-sergey_infra pull request #11
Opened 2022-07-27 12:39 UTC by klimenko-sergey

# Выполнено ДЗ "Ansible: работа с ролями и окружениями"

 - [+] Основное ДЗ
 - [-] Задание со *

## В процессе сделано:
 - Создана структура ролей с помощью Ansible Galaxy:
   ```
   ansible-galaxy init app
   ansible-galaxy init db
   ```
 - Созданы роли для базы данных и веб приложения
 - Файлы конфигурации Ansible адаптированы для использования ролей
 - Созданы окружения stage и prod в каталоге ansible/environments
 - Использована комьюнити роль jdauphant.nginx для проксирования веб приложения с целью доступа к нему по порту 80
 - Добавлены плейбуки credentials.yml для создания пользовательских учетных записей в ВМ, затем зашифрованы с помощью Ansible Vault:
   ```
   ansible-vault encrypt environments/prod/credentials.yml
   ansible-vault encrypt environments/stage/credentials.yml
   ```

## Как запустить проект:
 - В директории terraform/stage запустить команды:
   ```
   terraform destroy -auto-approve
   terraform apply-auto-approve
   ```
 - В директории ansible запустить командe:
   ```
   ansible-playbook playbooks/site.yml
   ```

## Как проверить работоспособность:
 - Открыть веб приложение:
   http://<public_ip_VM_with_app>

## PR checklist
 - [-] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2022-07-27 15:22 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Рекомендую свериться с результатами тестов
В папку с плейбуками вам нужно добавить инвентарь что бы ansible смог сделать проверки
Выглядит как приключение на 15 минут =)

2022-07-27 17:05 UTC, klimenko-sergey commented
@mrgreyves , добрый день!
Добавил [inventory.yml](https://github.com/Otus-DevOps-2022-05/klimenko-sergey_infra/blob/ansible-3/ansible/old/inventory.yml) в директорию playbooks. Но данное указание отсутствует в ДЗ.
Также прошу проверить пул реквест: https://github.com/Otus-DevOps-2022-05/klimenko-sergey_infra/pull/10
Все требования выполнил.

2022-07-28 05:10 UTC, klimenko-sergey commented
$ packer validate -var-file=packer/variables.json.example packer/app.json
Error: Failed to prepare build: "yandex"

1 error(s) occurred:

* playbook_file: ansible/packer_app.yml is invalid: stat ansible/packer_app.yml:
no such file or directory

Тест противоречит указанию ДЗ:
![изображение](https://user-images.githubusercontent.com/107353318/181425326-0e912efe-d966-4eff-9377-ab809d33874a.png)

2022-07-28 11:34 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
Апрув ^_^

2022-07-28 12:03 UTC, merged